### ISSUE TITLE
No resource, method, or local variable named `fail_or_error'

### ISSUE THREAD

**Issue by markunsworth** [chef-cookbooks/route53#108]
### Cookbook version
1.20

### Chef-client version
12.13.37

### Platform Details
Ubuntu 14.04 - running on AWS

### Scenario:
Set up a route53 record using the route53_record LWRP

```
    route53_record "create a public DNS record for web0.mydomain.com" do
        name  "web0.mydomain.com"
        value instance['public_dns']
        type  "CNAME"
        zone_id              node['zone_id']
        aws_access_key_id     nil
        aws_secret_access_key nil
        overwrite true
        ttl   300
        action :create       
    end
```

### Actual Result:

```
================================================================================
Error executing action `create` on resource 'route53_record[web0.mydomain.com]'
================================================================================
 
NameError
---------
No resource, method, or local variable named `fail_or_error' for `LWRP provider route53_record from cookbook route53 "web0.mydomain.com."'
 
Cookbook Trace:
---------------
/var/chef/runs/bddc0990-83ff-4b9b-bbb4-75f6de4452ca/local-mode-cache/cache/cookbooks/route53/providers/record.rb:166:in `rescue in change_record'
/var/chef/runs/bddc0990-83ff-4b9b-bbb4-75f6de4452ca/local-mode-cache/cache/cookbooks/route53/providers/record.rb:150:in `change_record'
/var/chef/runs/bddc0990-83ff-4b9b-bbb4-75f6de4452ca/local-mode-cache/cache/cookbooks/route53/providers/record.rb:179:in `block in class_from_file'
```

Looks like there's a spelling mistake in `route53/providers/record.rb` on [line 166](https://github.com/chef-cookbooks/route53/blob/fad812c38680e219baa4f5b76f3c70d7aa5d8d40/providers/record.rb#L166) It should be `fail_on_error` rather than `fail_or_error`

```
rescue Aws::Route53::Errors::ServiceError => e
  raise if fail_or_error
  Chef::Log.error "Error with #{action}request: #{request.inspect} ::: "
  Chef::Log.error e.message
end
```

**Comment by iennae** [comment]
Thanks for reporting. Looks to have been fixed with release 1.2.1 with this fix https://github.com/chef-cookbooks/route53/commit/8c9362fdf0cfb3b90faf0c92dbe4e46211594bfd
