### ISSUE TITLE
fog-aws 0.1.2 breaks this cookbook

### ISSUE THREAD

**Issue by asanger** [chef-cookbooks/route53#69]
Not sure if this is something that you guys want to investigate, but the 0.1.2 release of fog-aws seems to break this cookbook.

https://github.com/fog/fog-aws/issues/83

The solution in that issue is to replace fog with fog-aws. I know that PR #67 is about moving from fog to fog-aws, but there were concerns about breaking other functionality.

**Comment by plribeiro3000** [comment]
The issue is not related to have `fog-aws` instead of `fog` in the `Gemfile`.
In the case of `asset_sync` it was related to the specific require in the `Gemfile` like this:

```ruby
gem "fog", "~>1.20", require: "fog/aws/storage"
```

With the new structure that custom require is not needed anymore and it would fail if you still do.

The only usage of `fog` that i could find was in [this file](https://github.com/hw-cookbooks/route53/blob/develop/providers/record.rb). It does require `fog` which should work as expected. @asanger Can you provide more info regarding your error?

**Comment by asanger** [comment]
Here's an excerpt from my failed deploy log. Again, this was working until yesterday, so I do believe that it is in some way related to the 0.1.2 release.

```
[2015-04-08T20:39:46+00:00] INFO: Processing chef_gem[fog] action install (route53::default line 22)
[2015-04-08T20:39:46+00:00] INFO: Installing chef-gem fog = 1.27
[2015-04-08T20:40:29+00:00] INFO: Successfully installed net-scp-1.2.1
Successfully installed formatador-0.2.5
Successfully installed excon-0.45.1
Successfully installed fog-core-1.30.0
Successfully installed fog-json-1.0.1
Successfully installed fog-xml-0.1.2
Successfully installed fog-aws-0.1.2
Successfully installed inflecto-0.0.2
Successfully installed fog-brightbox-0.7.1
Successfully installed fog-softlayer-0.4.2
Successfully installed fog-sakuracloud-1.0.1
Successfully installed fog-radosgw-0.0.4
Successfully installed fog-profitbricks-0.0.2
Successfully installed fog-voxel-0.1.0
Successfully installed CFPropertyList-2.3.1
Successfully installed fission-0.5.0
Successfully installed fog-vmfusion-0.1.0
Successfully installed fog-terremark-0.1.0
Successfully installed fog-ecloud-0.1.1
Successfully installed fog-storm_on_demand-0.1.1
Successfully installed fog-atmos-0.1.0
Successfully installed fog-serverlove-0.1.2
Successfully installed fog-1.27.0
23 gems installed
 
[2015-04-08T20:40:29+00:00] INFO: Processing group[opsworks] action create (ssh_users::default line 1)
[2015-04-08T20:40:29+00:00] INFO: Processing template[/home/asanger/.ssh/authorized_keys] action create (ssh_users::default line 55)
[2015-04-08T20:40:29+00:00] INFO: Processing template[/etc/sudoers] action create (ssh_users::default line 31)
[2015-04-08T20:40:29+00:00] INFO: Processing template[/etc/sudoers.d/opsworks] action create (ssh_users::default line 41)
[2015-04-08T20:40:29+00:00] INFO: Processing template[/var/lib/aws/opsworks/TARGET_VERSION] action create (agent_version::default line 1)
[2015-04-08T20:40:29+00:00] INFO: template[/var/lib/aws/opsworks/TARGET_VERSION] updated file contents /var/lib/aws/opsworks/TARGET_VERSION
[2015-04-08T20:40:29+00:00] INFO: template[/var/lib/aws/opsworks/TARGET_VERSION] mode changed to 600
[2015-04-08T20:40:29+00:00] INFO: Processing template[/etc/hosts] action create (opsworks_stack_state_sync::hosts line 3)
[2015-04-08T20:40:29+00:00] INFO: Processing template[/etc/motd.opsworks-static] action create (opsworks_stack_state_sync::motd line 1)
[2015-04-08T20:40:29+00:00] INFO: Processing chef_gem[chef-sugar] action nothing (chef-sugar::default line 22)
[2015-04-08T20:40:29+00:00] INFO: Processing package[autoconf] action nothing (build-essential::_rhel line 108)
[2015-04-08T20:40:29+00:00] INFO: Processing package[bison] action nothing (build-essential::_rhel line 108)
[2015-04-08T20:40:29+00:00] INFO: Processing package[flex] action nothing (build-essential::_rhel line 108)
[2015-04-08T20:40:29+00:00] INFO: Processing package[gcc] action nothing (build-essential::_rhel line 108)
[2015-04-08T20:40:29+00:00] INFO: Processing package[gcc-c++] action nothing (build-essential::_rhel line 108)
[2015-04-08T20:40:29+00:00] INFO: Processing package[kernel-devel] action nothing (build-essential::_rhel line 108)
[2015-04-08T20:40:29+00:00] INFO: Processing package[make] action nothing (build-essential::_rhel line 108)
[2015-04-08T20:40:29+00:00] INFO: Processing package[m4] action nothing (build-essential::_rhel line 108)
[2015-04-08T20:40:29+00:00] INFO: Processing package[patch] action nothing (build-essential::_rhel line 108)
[2015-04-08T20:40:29+00:00] INFO: Processing package[libxml2-devel] action nothing (xml::default line 21)
[2015-04-08T20:40:29+00:00] INFO: Processing package[libxslt-devel] action nothing (xml::default line 21)
[2015-04-08T20:40:29+00:00] INFO: Processing chef_gem[nokogiri] action install (xml::ruby line 43)
[2015-04-08T20:40:29+00:00] INFO: Processing chef_gem[fog] action install (route53::default line 22)
[2015-04-08T20:40:29+00:00] INFO: Processing route53_record[marketing-innovators-staging.levelset.solutions] action create (dnsupdate::add line 4)
 
================================================================================
Error executing action `create` on resource 'route53_record[marketing-innovators-staging.levelset.solutions]'
================================================================================
 
 
NameError
---------
uninitialized constant Fog::AWS::CredentialFetcher
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/route53/providers/record.rb:82:in `require'
/var/lib/aws/opsworks/cache.stage2/cookbooks/route53/providers/record.rb:82:in `block in class_from_file'
 
 
Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/dnsupdate/recipes/add.rb
 
4: route53_record "create a record" do
5:   name  node[:opsworks][:instance][:hostname] + '.levelset.solutions'
6:   value Net::HTTP.get(URI.parse('http://169.254.169.254/latest/meta-data/public-ipv4'))
7:   type  "A"
8:   ttl   60
9:   zone_id               node[:dns_zone_id]
10:   aws_access_key_id     node[:custom_access_key]
11:   aws_secret_access_key node[:custom_secret_key]
12:   overwrite true
13:   action :create
14: end
 
 
 
Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/dnsupdate/recipes/add.rb:4:in `from_file'
 
route53_record("marketing-innovators-staging.levelset.solutions") do
action [:create]
retries 0
retry_delay 2
cookbook_name "dnsupdate"
recipe_name "add"
value "52.5.182.20"
type "A"
ttl 60
zone_id "<SNIP>"
aws_access_key_id "<SNIP>"
aws_secret_access_key "<SNIP>"
overwrite true
end
 
 
 
[2015-04-08T20:40:29+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-04-08T20:40:29+00:00] ERROR: Running exception handlers
[2015-04-08T20:40:29+00:00] ERROR: Exception handlers complete
[2015-04-08T20:40:29+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2015-04-08T20:40:29+00:00] ERROR: route53_record[marketing-innovators-staging.levelset.solutions] (dnsupdate::add line 4) had an error: NameError: uninitialized constant Fog::AWS::CredentialFetcher
[2015-04-08T20:40:29+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by plribeiro3000** [comment]
@asanger Can you provide the version of `route53` you are using?

I believe this is related to a older version of it that has [this require](https://github.com/hw-cookbooks/route53/blob/v0.3.5/providers/record.rb#L82).

**Comment by asanger** [comment]
I'm using version 0.4.0. A response over in the fog-aws repo suggested that it could be related to an OS update that occurred on the same day of the fog-aws 0.1.2, so I'd like to do some testing on the old OS to confirm.

**Comment by plribeiro3000** [comment]
@asanger Can you provide me a link where you got this information about an OS issue?

**Comment by asanger** [comment]
https://github.com/fog/fog-aws/issues/83#issuecomment-91347962

The OS upgrade was Amazon Linux 2015.03

**Comment by plribeiro3000** [comment]
got it. Thanks.

**Comment by asanger** [comment]
Very interesting. I was able to use this cookbook with fog-aws on the older version of the OS. I wonder if it's related to an updated aws-cli? The difference is only a minor bump from 1.7.13 to 1.7.14.

**Comment by benholtz** [comment]
Anyone have the fix?  I'm on the Amazon linux from 2014 and seeing the same issue

**Comment by plribeiro3000** [comment]
@benholtz Which version of `route53`are you using? Is it prior to `0.3.5`?

**Comment by benholtz** [comment]
depends "route53", "~> 0.4.0"

**Comment by plribeiro3000** [comment]
@benholtz Could you provide more info to help debug the issue?

**Comment by benholtz** [comment]
This is about as much detail as I can provide at this time:

[2015-04-20T19:23:56+00:00] INFO: Processing remote_file[/tmp/rubygems-2.2.2.tgz] action create (opsworks_rubygems::default line 1)
[2015-04-20T19:23:56+00:00] INFO: Processing execute[tar xfz rubygems-2.2.2.tgz] action run (opsworks_rubygems::default line 8)
[2015-04-20T19:23:56+00:00] INFO: Processing execute[Updating Rubygems to 2.2.2] action run (opsworks_rubygems::default line 16)
[2015-04-20T19:23:56+00:00] INFO: Processing execute[Clean up] action run (opsworks_rubygems::default line 25)
[2015-04-20T19:23:56+00:00] INFO: execute[Clean up] ran successfully
[2015-04-20T19:23:56+00:00] INFO: Processing package[xfsprogs] action install (ebs::default line 8)
[2015-04-20T19:23:56+00:00] INFO: Processing package[xfsprogs-devel] action install (ebs::default line 9)
[2015-04-20T19:23:56+00:00] INFO: Processing template[/etc/hosts] action create (opsworks_stack_state_sync::hosts line 3)
[2015-04-20T19:23:56+00:00] INFO: Processing template[/etc/motd.opsworks-static] action create (opsworks_stack_state_sync::motd line 1)
[2015-04-20T19:23:56+00:00] INFO: Processing chef_gem[chef-sugar] action nothing (chef-sugar::default line 22)
[2015-04-20T19:23:56+00:00] INFO: Processing package[autoconf] action nothing (build-essential::_rhel line 108)
[2015-04-20T19:23:56+00:00] INFO: Processing package[bison] action nothing (build-essential::_rhel line 108)
[2015-04-20T19:23:56+00:00] INFO: Processing package[flex] action nothing (build-essential::_rhel line 108)
[2015-04-20T19:23:56+00:00] INFO: Processing package[gcc] action nothing (build-essential::_rhel line 108)
[2015-04-20T19:23:56+00:00] INFO: Processing package[gcc-c++] action nothing (build-essential::_rhel line 108)
[2015-04-20T19:23:56+00:00] INFO: Processing package[kernel-devel] action nothing (build-essential::_rhel line 108)
[2015-04-20T19:23:56+00:00] INFO: Processing package[make] action nothing (build-essential::_rhel line 108)
[2015-04-20T19:23:56+00:00] INFO: Processing package[m4] action nothing (build-essential::_rhel line 108)
[2015-04-20T19:23:56+00:00] INFO: Processing package[patch] action nothing (build-essential::_rhel line 108)
[2015-04-20T19:23:56+00:00] INFO: Processing package[libxml2-devel] action nothing (xml::default line 21)
[2015-04-20T19:23:56+00:00] INFO: Processing package[libxslt-devel] action nothing (xml::default line 21)
[2015-04-20T19:23:56+00:00] INFO: Processing chef_gem[nokogiri] action install (xml::ruby line 43)
[2015-04-20T19:23:57+00:00] INFO: Processing chef_gem[fog] action install (route53::default line 22)
[2015-04-20T19:23:57+00:00] INFO: Processing route53_record[my_dns_record] action create (dnsupdate::add line 39)
 
================================================================================
Error executing action `create` on resource 'route53_record[my_dns_record]'
================================================================================
 
 
NameError
---------
uninitialized constant Fog::AWS::CredentialFetcher
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/route53/providers/record.rb:82:in `require'
/var/lib/aws/opsworks/cache.stage2/cookbooks/route53/providers/record.rb:82:in `block in class_from_file'
 
 
Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/dnsupdate/recipes/add.rb
 
39: route53_record "create a record" do
40:   name  node[:opsworks][:instance][:hostname] + '.' + domain_name
41:   value node[:opsworks][:instance][:private_ip]
42:   type  "A"
43:   ttl   60
44:   zone_id               dns_zone_id
45:   aws_key     node[:iam_key]
46:   aws_secret node[:iam_secret]
47:   overwrite true
48:   action :create
49: end
50: 
51: route53_record "create a record" do
52:   name  node[:opsworks][:instance][:hostname] + '.' + pub_domain_name
53:   value node[:opsworks][:instance][:private_ip]
54:   type  "A"
55:   ttl   60
56:   zone_id               pub_dns_zone_id
57:   aws_access_key_id     node[:dns_iam_key]
58:   aws_secret_access_key node[:dns_iam_secret]
59:   overwrite true
60:   action :create
61: end
 
 
 
Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/dnsupdate/recipes/add.rb:39:in `from_file'
 
route53_record("my_dns_record") do
action [:create]
retries 0
retry_delay 2
cookbook_name "dnsupdate"
recipe_name "add"
value "172.16.0.XXX"
type "A"
ttl 60
zone_id "ZONE_ID"
aws_access_key_id "KEY"
aws_secret_access_key "SECRET"
overwrite true
end

**Comment by benholtz** [comment]
Any traction here?  Our chef recipes are all broken.  I've tried many workarounds with no luck.  Help!

**Comment by benholtz** [comment]
@geemus Can you give us some advice here?

**Comment by geemus** [comment]
Hmm, not super obvious to me off-hand. Is there further stacktrace any where I could check out?

**Comment by plribeiro3000** [comment]
@benholtz @geemus I've reopend fog/fog-aws#67 and asked some more info to help debugging.

Perhaps we should move this conversation to there where we have access to create/close issues and commit fixes. Thoughts?

**Comment by waziers** [comment]
Any progress on this? All my cookbooks are also failing with an error similar to the one by @benholtz

**Comment by MikeStankavich** [comment]
Have you tried overriding default['route53']['fog_version'] = '1.27' to "1.29.0"? That worked for me.

**Comment by waziers** [comment]
That did work - thanks!

As a quick note for anyone else tackling this - I'm using this package through a custom cookbook on OpsWorks. Simply changing the attribute on an existing machine didn't fix the problem, I had to bring up a new machine from scratch and it worked. There must be some gem precedence issues.

**Comment by geemus** [comment]
Thanks for the extra details!

**Comment by baldurrensch** [comment]
That worked for me

**Comment by jdp** [comment]
Thanks for the tip @waziers, finally got it to work. Anyone know if there is a way to ssh in and clear out the gem? I tried digging around a bit, couldn't figure out where [`chef_gem`](https://docs.chef.io/resource_chef_gem.html) puts on the instance.

**Comment by vassav-nn** [comment]
Try add in OpsWorks "Custom JSON":
"route53":{"fog_version":"1.33.0"}

**Comment by greg-matthews-iugo** [comment]
Some more info from testing I have done regarding the `uninitialized constant Fog::AWS::CredentialFetcher` issue.

Looking in the stack trace from that issue I could see that fog 1.27.0 was being called even though 1.33.0 was in the 'Custom JSON' being used. This is due to fog 1.27.0 being installed from a previous run of the recipe on the instance. Looking in `/var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out` I could see it was calling from the 1.33.0 fog gem into the 1.27.0 fog-aws gem.

> /opt/aws/opsworks/current/vendor/bundle/ruby/2.0.0/gems/fog-1.27.0/lib/fog/aws.rb:2:in 'require'
> /opt/aws/opsworks/current/vendor/bundle/ruby/2.0.0/gems/fog-1.27.0/lib/fog/aws.rb:2:in '< top (required) >'
> /opt/aws/opsworks/current/vendor/bundle/ruby/2.0.0/gems/fog-1.33.0/lib/fog.rb:23:in 'require'
> /opt/aws/opsworks/current/vendor/bundle/ruby/2.0.0/gems/fog-1.33.0/lib/fog.rb:23:in '< top (required) >'

To fix this I had to manually remove the fog 1.27.0 gem so that only the 1.33.0 gem was being used, which did solve the issue.

**Comment by geemus** [comment]
@greg-matthews-iugo thanks for the detailed update.

**Comment by tas50** [comment]
Fog has been replaced with the aws-sdk so this is no longer a valid issue
