### ISSUE TITLE
NoMethodError: undefined method `body' for #<Fog

### ISSUE THREAD

**Issue by jslusher** [chef-cookbooks/route53#73]
I seem to have the proper version of fog installed. fog-aws 1.2 is installed, and I saw a couple of separate issues that might be related. I'm getting a different error though, regarding the body method that is being called in the provider:

``` 
                   * route53_record[webapp1] action create[2015-05-12T17:22:50+00:00] INFO: Processing route53_record[webapp1] action create (wrapper-cookbook::default line 17)
                  WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
                  [2015-05-12T17:22:51+00:00] INFO: Getting record: webapp1. A


                      ================================================================================
                      Error executing action `create` on resource 'route53_record[webapp1]'
                      ================================================================================

                      NoMethodError
                      -------------
                      undefined method `body' for #<Fog::DNS::AWS::Error:0x0000000a2003c8>

                      Cookbook Trace:
                      ---------------
                      /var/chef/cache/cookbooks/route53/providers/record.rb:53:in `zone'
                      /var/chef/cache/cookbooks/route53/providers/record.rb:69:in `record'
                      /var/chef/cache/cookbooks/route53/providers/record.rb:114:in `block in class_from_file'
```

**Comment by mansona** [comment]
I'm getting the same issue, have you had a look into what might be causing this?

**Comment by mbenziane** [comment]
I'm getting the same thing.

**Comment by eherot** [comment]
Seems this is (or rather was) actually a Fog issue: fog/fog-aws#112

**Comment by tas50** [comment]
Fog has been replaced with the aws-sdk so this is no longer a valid issue
