### ISSUE TITLE
SignatureDoesNotMatch Error

### ISSUE THREAD

**Issue by john-mcgowan-wowza** [chef-cookbooks/route53#98]
I'm getting a SignatureDoesNotMatch error when trying to use the route53_record resource.  I'm not passing an access key or secret access key as I'm relying on an IAM role for authentication.

Am I missing something, or should this just work?

This is what I see in my Chef logs...

```
Aws::Route53::Errors::SignatureDoesNotMatch
-------------------------------------------
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/2013-04-01/hostedzone/rrset
name=wsd-wiki.wowza.com.
host:route53.amazonaws.com
x-amz-content-sha256:xxx
x-amz-date:20160930T194028Z
x-amz-security-xxxxxx=

host;x-amz-content-sha256;x-amz-date;x-amz-security-token
xxxxxxx'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20160930T194028Z
20160930/us-east-1/route53/aws4_request
xxxxxxx'

```

**Comment by jimmy-biznessapps** [comment]
Also seeing this. I saw a similar issue in the AWS CLI until I updated it to the latest version.

**Comment by gopisaba** [comment]
+1

**Comment by prozacUa** [comment]
Anybody solved this? @gopisaba @john-mcgowan-wowza

**Comment by iennae** [comment]
Folks who are experiencing this, did updating the aws cli remedy the problem or are you still having the issue?

**Comment by scalp42** [comment]
@iennae this is related to Chef not the aws-cli 

I'm seeing the same issue as well but using tokens here (instead of IAM profiles for testing):

```
Recipe: fs-jumphost::route53
  * route53_record[infra-jump.guacamole.io] action create

    ================================================================================
    Error executing action `create` on resource 'route53_record[infra-jump.guacamole.io]'
    ================================================================================

    Aws::Route53::Errors::SignatureDoesNotMatch
    -------------------------------------------
    The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

    The Canonical String for this request should have been
    'GET
    /2013-04-01/hostedzone/rrset
    name=infra-jump.guacamole.io.
    host:route53.amazonaws.com
    x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    x-amz-date:20170322T234657Z

    host;x-amz-content-sha256;x-amz-date
    e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'

    The String-to-Sign should have been
    'AWS4-HMAC-SHA256
    20170322T234657Z
    20170322/us-east-1/route53/aws4_request
    7ad5823c72748267b77cf59fa12e239bae6edf26e2409923111155c87c11f26a'

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/route53/providers/record.rb:68:in `current_resource_record_set'
    /var/chef/cache/cookbooks/route53/providers/record.rb:118:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/fs-jumphost/recipes/route53.rb

     14:   route53_record %|Route53 => '#{node['fs-jumphost']['route53']['record']}' (A record)| do
     15:     name  node['fs-jumphost']['route53']['record']
     16:     value node['fs-jumphost']['route53']['eip']
     17:     ttl 60
     18:     type  'A'
     19:     zone_id               node['route53']['zone_id']
     20:     aws_access_key_id     node['route53']['aws_access_key_id']
     21:     aws_secret_access_key node['route53']['aws_secret_access_key']
     22:     aws_region            node['ec2']['placement_availability_zone'][0..-2]
     23:     overwrite true
     24:     action node[cookbook_name]['route53']['enabled'] ? :create : :delete
     25:     only_if { lazy { node['vagrant'].nil? || node['vagrant'].empty? } }
     26:   end
     27: end
```

**Comment by scalp42** [comment]
Error is misleading as in my case the `zone_id` was not correct!

Hopefully it helps 🍶

**Comment by tas50** [comment]
The route53_record resource in this cookbook has been merged into the aws cookbook itself and improved quite a bit. There's also been a new aws_route53_zone resource added for creating / deleting zones. At this point in time we're deprecating this cookbook in favor of the aws cookbook. If you're still having this issue feel free to open it up in the aws cookbook.
